### ISSUE TITLE
Cause: couldn't make a guess for sakout.mehdi.StateViews.library.StateView

### ISSUE THREAD

**Issue by Isma3ilMohamed** [medyo/StateViews#2]
hey @medyo 
i want to use your lib with data binding
first i declare it in xml like that
<sakout.mehdi.StateViews.StateView
but it give me this issue
`error: cannot find symbol class StateViews`
when i see issues lib i try to edit it like that
<sakout.mehdi.StateViews.libbrary.StateView
it give me this issue 
`Cause: couldn't make a guess for sakout.mehdi.StateViews.library.StateView`
i want to use your lib
so can you help me please !

**Comment by medyo** [comment]
Hi @EsmaeilMohamed,

I think there is an issue in my declaration, I'll fix it in the coming version.
in the meantime, you can start using it by calling `sakout.mehdi.pagestatus.library.PageStatusView`

**Comment by Isma3ilMohamed** [comment]
Hey @medyo 
thanks for your reply
and i 'll wait you and please 
update your lib docs

**Comment by medyo** [comment]
the version `0.2` is working perfectly, by calling `<sakout.mehdi.StateViews.StateView />`, please update the dependency

**Comment by 1476ww** [comment]
- @Isma3ilMohamed
